In [1]:
import numpy as np
print(np.__version__)

1.19.2


In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [6]:
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
arr = np.arange(10)
arr.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


In [10]:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [13]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [14]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [15]:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [21]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [22]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [24]:
a = np.arange(15)
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [26]:
a[(a >= 5) & (a <= 10)]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [32]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [34]:
arr = np.arange(9).reshape(3,3)
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[8.32319079 9.97517079 7.31604765]
 [8.29823374 7.3479277  6.91650672]
 [9.20584639 5.87445141 8.48358474]
 [7.74886749 9.73702075 6.31186275]
 [5.66072504 6.77032989 9.38652114]]


In [36]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.437, 0.266, 0.128],
       [0.59 , 0.105, 0.816],
       [0.697, 0.482, 0.494],
       [0.708, 0.023, 0.662]])

In [37]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [61]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [62]:
print(a.argsort())

[ 4 13  5 ...  3 10 15]


In [63]:
np.argpartition(-a, 5)[:5]

array([15, 10,  3,  7, 18])

In [64]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [65]:
np.clip(a, a_min=10, a_max=30)

array([27.63, 14.64, 21.8 , ..., 10.  , 30.  , 14.43])

In [66]:
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.63 14.64 21.8  ... 10.   30.   14.43]


In [71]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)


In [72]:
print('array_of_arrays: ', array_of_arrays)

array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]


In [73]:
np.random.seed(10)
a = np.random.randint(20, size=10)

In [74]:
print('Array: ', a)

Array:  [ 9  4 15 ...  8  9  0]


In [75]:
print(a.argsort().argsort())
print('Array: ', a)

[4 2 6 ... 3 5 1]
Array:  [ 9  4 15 ...  8  9  0]


In [76]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])

In [77]:
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [78]:
print(a.ravel().argsort().argsort().reshape(a.shape))

[[4 2 6 0 8]
 [7 9 3 5 1]]


In [79]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a


array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [80]:
np.amax(a, axis=1)

array([9, 8, 6, 3, 9])

In [81]:
np.apply_along_axis(np.max, arr=a, axis=1)

array([9, 8, 6, 3, 9])

In [82]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])